//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.21 at 11:10:07 AM UTC 
//


package com.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Critere1" minOccurs="0"/&gt;
 *         &lt;element ref="{}Critere2" minOccurs="0"/&gt;
 *         &lt;element ref="{}Critere3" minOccurs="0"/&gt;
 *         &lt;element ref="{}Critere4" minOccurs="0"/&gt;
 *         &lt;element ref="{}Critere5" minOccurs="0"/&gt;
 *         &lt;element ref="{}Critere6" minOccurs="0"/&gt;
 *         &lt;element ref="{}Critere7" minOccurs="0"/&gt;
 *         &lt;element ref="{}Critere8" minOccurs="0"/&gt;
 *         &lt;element ref="{}Critere9" minOccurs="0"/&gt;
 *         &lt;element ref="{}Critere10" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "critere1",
    "critere2",
    "critere3",
    "critere4",
    "critere5",
    "critere6",
    "critere7",
    "critere8",
    "critere9",
    "critere10"
})
@XmlRootElement(name = "Critere")
public class Critere {

    @XmlElement(name = "Critere1")
    protected Critere1 critere1;
    @XmlElement(name = "Critere2")
    protected Critere2 critere2;
    @XmlElement(name = "Critere3")
    protected Critere3 critere3;
    @XmlElement(name = "Critere4")
    protected Critere4 critere4;
    @XmlElement(name = "Critere5")
    protected Critere5 critere5;
    @XmlElement(name = "Critere6")
    protected Critere6 critere6;
    @XmlElement(name = "Critere7")
    protected Critere7 critere7;
    @XmlElement(name = "Critere8")
    protected Critere8 critere8;
    @XmlElement(name = "Critere9")
    protected Critere9 critere9;
    @XmlElement(name = "Critere10")
    protected Critere10 critere10;

    /**
     * Gets the value of the critere1 property.
     * 
     * @return
     *     possible object is
     *     {@link Critere1 }
     *     
     */
    public Critere1 getCritere1() {
        return critere1;
    }

    /**
     * Sets the value of the critere1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Critere1 }
     *     
     */
    public void setCritere1(Critere1 value) {
        this.critere1 = value;
    }

    /**
     * Gets the value of the critere2 property.
     * 
     * @return
     *     possible object is
     *     {@link Critere2 }
     *     
     */
    public Critere2 getCritere2() {
        return critere2;
    }

    /**
     * Sets the value of the critere2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Critere2 }
     *     
     */
    public void setCritere2(Critere2 value) {
        this.critere2 = value;
    }

    /**
     * Gets the value of the critere3 property.
     * 
     * @return
     *     possible object is
     *     {@link Critere3 }
     *     
     */
    public Critere3 getCritere3() {
        return critere3;
    }

    /**
     * Sets the value of the critere3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Critere3 }
     *     
     */
    public void setCritere3(Critere3 value) {
        this.critere3 = value;
    }

    /**
     * Gets the value of the critere4 property.
     * 
     * @return
     *     possible object is
     *     {@link Critere4 }
     *     
     */
    public Critere4 getCritere4() {
        return critere4;
    }

    /**
     * Sets the value of the critere4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Critere4 }
     *     
     */
    public void setCritere4(Critere4 value) {
        this.critere4 = value;
    }

    /**
     * Gets the value of the critere5 property.
     * 
     * @return
     *     possible object is
     *     {@link Critere5 }
     *     
     */
    public Critere5 getCritere5() {
        return critere5;
    }

    /**
     * Sets the value of the critere5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Critere5 }
     *     
     */
    public void setCritere5(Critere5 value) {
        this.critere5 = value;
    }

    /**
     * Gets the value of the critere6 property.
     * 
     * @return
     *     possible object is
     *     {@link Critere6 }
     *     
     */
    public Critere6 getCritere6() {
        return critere6;
    }

    /**
     * Sets the value of the critere6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Critere6 }
     *     
     */
    public void setCritere6(Critere6 value) {
        this.critere6 = value;
    }

    /**
     * Gets the value of the critere7 property.
     * 
     * @return
     *     possible object is
     *     {@link Critere7 }
     *     
     */
    public Critere7 getCritere7() {
        return critere7;
    }

    /**
     * Sets the value of the critere7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Critere7 }
     *     
     */
    public void setCritere7(Critere7 value) {
        this.critere7 = value;
    }

    /**
     * Gets the value of the critere8 property.
     * 
     * @return
     *     possible object is
     *     {@link Critere8 }
     *     
     */
    public Critere8 getCritere8() {
        return critere8;
    }

    /**
     * Sets the value of the critere8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Critere8 }
     *     
     */
    public void setCritere8(Critere8 value) {
        this.critere8 = value;
    }

    /**
     * Gets the value of the critere9 property.
     * 
     * @return
     *     possible object is
     *     {@link Critere9 }
     *     
     */
    public Critere9 getCritere9() {
        return critere9;
    }

    /**
     * Sets the value of the critere9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Critere9 }
     *     
     */
    public void setCritere9(Critere9 value) {
        this.critere9 = value;
    }

    /**
     * Gets the value of the critere10 property.
     * 
     * @return
     *     possible object is
     *     {@link Critere10 }
     *     
     */
    public Critere10 getCritere10() {
        return critere10;
    }

    /**
     * Sets the value of the critere10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Critere10 }
     *     
     */
    public void setCritere10(Critere10 value) {
        this.critere10 = value;
    }

}
