//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.21 at 11:10:07 AM UTC 
//


package com.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}LstReaContrats"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lstReaContrats"
})
@XmlRootElement(name = "Delegataire")
public class Delegataire {

    @XmlElement(name = "LstReaContrats", required = true)
    protected LstReaContrats lstReaContrats;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the lstReaContrats property.
     * 
     * @return
     *     possible object is
     *     {@link LstReaContrats }
     *     
     */
    public LstReaContrats getLstReaContrats() {
        return lstReaContrats;
    }

    /**
     * Sets the value of the lstReaContrats property.
     * 
     * @param value
     *     allowed object is
     *     {@link LstReaContrats }
     *     
     */
    public void setLstReaContrats(LstReaContrats value) {
        this.lstReaContrats = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
