//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.21 at 11:10:07 AM UTC 
//


package com.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}DateGen" minOccurs="0"/&gt;
 *         &lt;element ref="{}DateEnvoi" minOccurs="0"/&gt;
 *         &lt;element ref="{}IdEmetteur"/&gt;
 *         &lt;element ref="{}PeriodeEch"/&gt;
 *         &lt;element ref="{}DateArrete" minOccurs="0"/&gt;
 *         &lt;element ref="{}LstDelegataires"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="type" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="ATT"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="NumVer" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dateGen",
    "dateEnvoi",
    "idEmetteur",
    "periodeEch",
    "dateArrete",
    "lstDelegataires"
})
@XmlRootElement(name = "Pivot")
public class Pivot {

    @XmlElement(name = "DateGen")
    protected DateGen dateGen;
    @XmlElement(name = "DateEnvoi")
    protected DateEnvoi dateEnvoi;
    @XmlElement(name = "IdEmetteur", required = true)
    protected IdEmetteur idEmetteur;
    @XmlElement(name = "PeriodeEch", required = true)
    protected PeriodeEch periodeEch;
    @XmlElement(name = "DateArrete")
    protected DateArrete dateArrete;
    @XmlElement(name = "LstDelegataires", required = true)
    protected LstDelegataires lstDelegataires;
    @XmlAttribute(name = "type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "NumVer", required = true)
    protected String numVer;

    /**
     * Gets the value of the dateGen property.
     * 
     * @return
     *     possible object is
     *     {@link DateGen }
     *     
     */
    public DateGen getDateGen() {
        return dateGen;
    }

    /**
     * Sets the value of the dateGen property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateGen }
     *     
     */
    public void setDateGen(DateGen value) {
        this.dateGen = value;
    }

    /**
     * Gets the value of the dateEnvoi property.
     * 
     * @return
     *     possible object is
     *     {@link DateEnvoi }
     *     
     */
    public DateEnvoi getDateEnvoi() {
        return dateEnvoi;
    }

    /**
     * Sets the value of the dateEnvoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateEnvoi }
     *     
     */
    public void setDateEnvoi(DateEnvoi value) {
        this.dateEnvoi = value;
    }

    /**
     * Gets the value of the idEmetteur property.
     * 
     * @return
     *     possible object is
     *     {@link IdEmetteur }
     *     
     */
    public IdEmetteur getIdEmetteur() {
        return idEmetteur;
    }

    /**
     * Sets the value of the idEmetteur property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdEmetteur }
     *     
     */
    public void setIdEmetteur(IdEmetteur value) {
        this.idEmetteur = value;
    }

    /**
     * Gets the value of the periodeEch property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodeEch }
     *     
     */
    public PeriodeEch getPeriodeEch() {
        return periodeEch;
    }

    /**
     * Sets the value of the periodeEch property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodeEch }
     *     
     */
    public void setPeriodeEch(PeriodeEch value) {
        this.periodeEch = value;
    }

    /**
     * Gets the value of the dateArrete property.
     * 
     * @return
     *     possible object is
     *     {@link DateArrete }
     *     
     */
    public DateArrete getDateArrete() {
        return dateArrete;
    }

    /**
     * Sets the value of the dateArrete property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateArrete }
     *     
     */
    public void setDateArrete(DateArrete value) {
        this.dateArrete = value;
    }

    /**
     * Gets the value of the lstDelegataires property.
     * 
     * @return
     *     possible object is
     *     {@link LstDelegataires }
     *     
     */
    public LstDelegataires getLstDelegataires() {
        return lstDelegataires;
    }

    /**
     * Sets the value of the lstDelegataires property.
     * 
     * @param value
     *     allowed object is
     *     {@link LstDelegataires }
     *     
     */
    public void setLstDelegataires(LstDelegataires value) {
        this.lstDelegataires = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the numVer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumVer() {
        return numVer;
    }

    /**
     * Sets the value of the numVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumVer(String value) {
        this.numVer = value;
    }

}
