//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.21 at 11:10:07 AM UTC 
//


package com.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="mntAssiette" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="txAppPrime" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="typeAssiette" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Prime")
public class Prime {

    @XmlAttribute(name = "mntAssiette")
    protected String mntAssiette;
    @XmlAttribute(name = "txAppPrime")
    protected String txAppPrime;
    @XmlAttribute(name = "typeAssiette")
    protected String typeAssiette;

    /**
     * Gets the value of the mntAssiette property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMntAssiette() {
        return mntAssiette;
    }

    /**
     * Sets the value of the mntAssiette property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMntAssiette(String value) {
        this.mntAssiette = value;
    }

    /**
     * Gets the value of the txAppPrime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxAppPrime() {
        return txAppPrime;
    }

    /**
     * Sets the value of the txAppPrime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxAppPrime(String value) {
        this.txAppPrime = value;
    }

    /**
     * Gets the value of the typeAssiette property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeAssiette() {
        return typeAssiette;
    }

    /**
     * Sets the value of the typeAssiette property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeAssiette(String value) {
        this.typeAssiette = value;
    }

}
